export const HEADINGS = {
  AGENCIES: {
    TITLE: "Agencies",
    SUBTITLE: "Manage all agencies",
  },
  AGENTS: {
    TITLE: "Agents",
    SUBTITLE: "Manage all agents",
  },
  CASES: {
    TITLE: "Cases",
    SUBTITLE: "Manage all cases",
  },
  SERVICES: {
    TITLE: "Services",
    SUBTITLE: "Manage all services",
  },
  ASSISTANCE: {
    TITLE: "Assistance",
    SUBTITLE: "Manage Assistance Records",
  },
  PERSONAL_INFO: {
    TITLE: "Personal Info",
    SUBTITLE: "View and edit personal information",
  },
  RELATIONSHIPS: {
    TITLE: "Relationships",
    SUBTITLE: "Manage relationships",
  },
  CATEGORIES: {
    TITLE: "Categories",
    SUBTITLE: "Manage all categories and subcategories",
  },
  OUTCOMES: {
    TITLE: "Outcomes",
  },
  BARCODES: {
    TITLE: "Barcodes",
    SUBTITLE: "Manage and print barcodes for your agency's services and items",
  },
  BED_ASSIGNMENTS: {
    TITLE: "Bed Assignments",
  },
  BED_MANAGEMENT: {
    TITLE: "Bed Requests / Waiting List",
  },
  SITE_BED_MANAGEMENT: {
    TITLE: "Site Bed Management",
  },
  REFERRALS: {
    TITLE: "Referrals",
    SUBTITLE: "Manage all referrals",
  },
};

export const ERROR_MESSAGES = {
  FETCH: {
    CASES: "Failed to fetch cases.",
    CATEGORIES: "Failed to fetch categories.",
    GENERIC: "An error occurred while fetching data.",
    NETWORK: "Network error occurred. Please check your connection.",
    RECENT_CASES_FAILED: "Failed to load recent cases.",
    RECENT_SEARCHES_FAILED: "Failed to load recent searches.",
    ASSESSMENTS: "Failed to fetch assessments.",
  },
  FORM: {
    REQUIRED: "This field is required",
    INVALID_EMAIL: "Please enter a valid email address",
    INVALID_PHONE: "Please enter a valid phone number",
    PASSWORD_MISMATCH: "Passwords do not match",
    UNSUPPORTED_FILE_TYPE: "Unsupported file type",
    FILE_SIZE_EXCEEDS: (maxSize: number) => `File must be <= ${maxSize}MB`,
    NUMBER_MIN: (min: number) => `Value must be at least ${min}`,
    NUMBER_MAX: (max: number) => `Value must be at most ${max}`,
    NUMBER_MAX_DECIMALS: (max: number) =>
      `Value can have at most ${max} decimal places`,
    NUMBER_MAX_TOTAL_DIGITS: (max: number) =>
      `Value can have at most ${max} digits in total`,
    MAX_LENGTH: (length: number, fieldName: string) =>
      `${fieldName} must be at most ${length} characters`,
    MIN_LENGTH: (min: number, fieldName: string) =>
      `${fieldName} must be at least ${min} characters`,
    FUTURE_DATE_NOT_ALLOWED: (fieldName: string) =>
      `${fieldName} cannot be in the future`,
    INVALID_SSN_FORMAT: "SSN must be in the format XXX-XX-XXXX",
    INVALID_ZIP_FORMAT: "Zip must be in format XXXXX or XXXXX-XXXX",
    INVALID_PHONE_FORMAT:
      "Phone number must be in a valid format (e.g., (123) 456-7890)",
    AT_LEAST_ONE_FIELD_REQUIRED: "At least one search field must be filled",
    INVALID_TAXONOMY_CODE:
      "Taxonomy code can only contain letters, numbers, and hyphens",
    POSITIVE_NUMBER: "Must be a positive number",
  },
  AUTH: {
    INVALID_CREDENTIALS: "Invalid email or password",
    SESSION_EXPIRED: "Your session has expired. Please login again.",
    UNAUTHORIZED: "You are not authorized to perform this action",
    PERMISSION_DENIED_UPDATE_CATEGORIES:
      "You don't have permission to update categories.",
    PERMISSION_DENIED_CREATE_CATEGORIES:
      "You don't have permission to create categories.",
    PERMISSION_DENIED_DELETE_CATEGORIES:
      "You don't have permission to delete categories.",
  },
  DELETE: {
    SUBCATEGORY: "Failed to delete subcategory.",
    GENERIC: "An error occurred while deleting the item.",
  },
  SAVE: {
    GENERIC: "Error saving data. Please try again.",
  },
  ASSESSMENT: {
    FIELD_NAME_REQUIRED: "Field name is required",
    FIELD_NAME_MIN: "Field name must be at least 2 characters",
    FIELD_NAME_MAX: "Field name must be at most 100 characters",
    FIELD_TYPE_REQUIRED: "Field type is required",
  },
};

export const STATIC_TEXTS = {
  COMMON: {
    LOADING: "Loading...",
    NO_DATA: "No data found",
    SAVE: "Save",
    CANCEL: "Cancel",
    DELETE: "Delete",
    EDIT: "Edit",
    PRINT: "Print",
    ADD: "Add",
    VIEW_MORE: "View More",
    VIEW_LESS: "View Less",
    SEARCH: "Search",
    FILTER: "Filter",
    NOT_PROVIDED: "Not Provided",
    BACK: "Back",
    CLOSE: "Close",
    SAVE_CHANGES: "Save Changes",
    SAVE_AND_ADD_ANOTHER: "Save & Add another",
    SELECT_DATE_TIME: "Select date and time",
    SELECT_DEADLINE_DATE: "Select deadline date",
    SELECT_SERVICE: "Select Service",
    NO_CASES_FOUND: "No cases found.",
    DUMMY_CONTACT_NAME: "Andre Devine",
    DUMMY_CONTACT_ADDRESS_LINE1: "223 Calhoun Drive",
    DUMMY_CONTACT_ADDRESS_LINE2: "Madison, MS 39110",
    NO_HOURS_SPECIFIED: "No hours specified",
    DUMMY_PHONE: "No phone specified",
    DUMMY_SERVICE_TITLE: "Meal Service",
    DUMMY_SERVICE_DESCRIPTION:
      "Provide meal service to existing shelters that support the homeless or those recovering from addiction",
    VERIFY_CASE_MESSAGE: "Be sure to verify",
    VERIFY_CASE_IDENTIFICATION: "this is the correct case for",
    VERIFY_CASE_USING_ID: "using a form of identification.",
    SHOW_ALL: "Show All",
    NEXT: "Next",
    ADD_COMMENT: "Add Comment",
    EDIT_COMMENT: "Edit Comment",
    DELETE_COMMENT: "Delete Comment",
    DELETE_COMMENT_DESC: "Are you sure you want to delete this comment?",
    FAILED_TO_DOWNLOAD_FILE: "Failed to download file.",
    COMMENT: "Comment",
    AND: "and",
    AT: "at",
    SELECT_OPTION: "Select Option",
    NO_FILTERS_FOUND: "No filters found.",
  },
  ERROR_MESSAGES: {
    FETCH: {
      CASES: "Failed to fetch cases.",
      GENERIC: "An error occurred while fetching data.",
      NETWORK: "Network error occurred. Please check your connection.",
      RECENT_CASES_FAILED: "Failed to load recent cases.",
      RECENT_SEARCHES_FAILED: "Failed to load recent searches.",
    },
    FORM: {
      REQUIRED: "This field is required",
      INVALID_EMAIL: "Please enter a valid email address",
      INVALID_PHONE: "Please enter a valid phone number",
      PASSWORD_MISMATCH: "Passwords do not match",
      UNSUPPORTED_FILE_TYPE: "Unsupported file type",
      FILE_SIZE_EXCEEDS: (maxSize: number) => `File must be <= ${maxSize}MB`,
      MAX_LENGTH: (length: number, fieldName: string) =>
        `${fieldName} must be at most ${length} characters`,
      MIN_LENGTH: (min: number, fieldName: string) =>
        `${fieldName} must be at least ${min} characters`,
      FUTURE_DATE_NOT_ALLOWED: (fieldName: string) =>
        `${fieldName} cannot be in the future`,
      INVALID_SSN_FORMAT: "SSN must be in the format XXX-XX-XXXX",
      INVALID_ZIP_FORMAT: "Zip must be in format XXXXX or XXXXX-XXXX",
      INVALID_PHONE_FORMAT:
        "Phone number must be in a valid format (e.g., (123) 456-7890)",
      AT_LEAST_ONE_FIELD_REQUIRED: "At least one search field must be filled",
    },
    AUTH: {
      INVALID_CREDENTIALS: "Invalid email or password",
      SESSION_EXPIRED: "Your session has expired. Please login again.",
      UNAUTHORIZED: "You are not authorized to perform this action",
    },
  },
  AGENCY: {
    SHOW_DISABLED: "Show Disabled Agents",
    ADD_AGENT: "Add New Agent",
    EDIT_AGENCY: "Edit Agency Information",
    CHANGE_PASSWORD: "Change Password",
    DELETE_CONFIRM: "Are you sure you want to delete this agent?",
    BED_MANAGEMENT: {
      TITLE: "Bed Requests / Waiting List",
      ADD_REQUEST: "Add Request",
      SELECT_CASE: "Select Case",
      ADD_BED_REQUEST: "Add Bed Request",
      NAME_CASE_SEARCH: "Name or case # search...",
      ADD_NEW_PERSON: " Add a new person to CrossRoads",
      BED_TYPE: "Bed Type",
      UNITS: "Units",
      REQUESTED_BY: "Requested By",
      ADD_BED_CHECK_IN: "Add Bed Check In",
      BED_CHECK_OUT: "Bed Check Out",
      PRINT_BED_LIST: "Print Bed List",
      DELETE_BED_REQUEST: "Delete / Deny Bed Request",
    },
  },
  CASE: {
    PERSONAL_INFO: "Personal Information",
    CONTACT_INFO: "Contact Information",
    INCOME_INFO: "Income Information",
    ADDITIONAL_DETAILS: "Additional Details",
    HISTORY: "History of Modifications",
    HISTORY_CHANGED_SUFFIX: "changed",
    HISTORY_TO_SEPARATOR: "to",
    NO_HISTORY: "No History found",
    NO_ADDRESS: "No address provided",
    IMAGE: {
      TITLE: "Case Image",
      DELETE_TITLE: "Delete Case Image",
      UPLOAD_SUCCESS: "Case image uploaded successfully!",
      UPLOAD_ERROR: "Failed to upload case image.",
      DELETE_SUCCESS: "Case image deleted successfully!",
      DELETE_ERROR: "Failed to delete case image.",
      DELETE_CONFIRM: "Are you sure you want to delete the case image?",
      NO_IMAGE: "No image provided",
    },
    NO_CASES_FOUND: "No Cases Found",
  },
  ASSISTANCE: {
    ADD_REQUEST: "Add Request/Referral",
    ADD_ASSISTANCE: "Add Assistance",
    SHOW_ALL: "Show all",
    SHOW_ACTIVE: "Show active",
    SHOW_COMPLETED: "Show completed",
    FILTER_BY: "Filter By",
    EDIT_ASSISTANCE: "Edit Assistance",
    ADD_MULTIPLE_ASSISTANCE: "Add Multiple Assistance",
    ADD_REQUEST_REFERRALS_BUTTON: "Add request/Refferals",
    ADD_ASSISTANCE_TO_CASES: "Add this assistance to the following cases:",
    CONFIRM_DELETE_TITLE: (type: string) => `Confirm ${type} Deletion`,
    CONFIRM_DELETE_MESSAGE: (type: string) =>
      `Are you sure you want to permanently delete this ${type} record? This action cannot be undone.`,
    DELETE_BUTTON: (type: string) => `Delete ${type}`,
    CREATED_SUCCESS: "Assistance record created successfully",
    UPDATED_SUCCESS: "Assistance record updated successfully",
    DELETED_SUCCESS: "Assistance record deleted successfully",
    FETCH_ERROR: "Failed to fetch assistance records",
    CREATE_ERROR: "Failed to create assistance record",
    UPDATE_ERROR: "Failed to update assistance record",
    DELETE_ERROR: "Failed to delete assistance record",
    MISSING_INFO:
      "Unable to create assistance. Please ensure you are properly logged in to GHL with an active location selected.",
    MISSING_DELETE_INFO: "Missing information for deletion.",
    RECEIVED_BY: "Received by",
    FOR: "for",
    TO: "to",
    AT: "at",
    ON: "on",
    ASSISTANCE_FOR: "assistance for",
    A_REQUEST_FOR: "a request for",
    PRIVATE: "PRIVATE",
    NO_RECORDS: "No assistance records found.",
    MULTIPLE_CREATED_SUCCESS: "Assistance records created successfully",
    MULTIPLE_CREATE_ERROR: "Failed to create multiple assistance records",
    MISSING_LOCATION: "User must have an active location selected.",
    MISSING_CASE_SELECTION:
      "Unable to create assistance. Please ensure you are properly logged in to GHL with an active location selected and at least one case is selected.",
  },
  RELATIONSHIPS: {
    ADD_RELATIONSHIP: "Add Relationship",
    EDIT_RELATIONSHIP: "Edit Relationship",
    RELATED_TO: "Related to",
  },
  CATEGORIES: {
    ADD_CATEGORY: "Add Category",
    EDIT_CATEGORY: "Edit Category",
    SAVE_CHANGES: "Save Changes",
    DELETE_CATEGORY: "Delete Category",
    DELETE_CATEGORY_CONFIRM:
      "Are you sure you want to delete this category? This action cannot be undone.",
    DELETE_SUCCESS: "Category deleted successfully",
    UPDATE_SUCCESS: "Category updated successfully",
    CREATE_SUCCESS: "Category created successfully",
    SECTION: "Section",
    DESCRIPTION: "Description",
    DEFAULT_AMOUNT: "Default Amount",
    FIXED_VALUE: "Fixed Value",
    VISIBILITY: {
      ALL_AGENCIES: "All Agencies",
      AGENCY_ONLY: "Agency Only",
    },
    MANAGE_CATEGORIES: "Manage Categories",
  },
  OUTCOMES: {
    MANAGE_SECTIONS: "Manage Sections",
    MANAGE_STATUSES: "Manage Statuses",
    ADD_GOAL: "Add Goal",
    SAVE_GOAL: "Save Goal",
    ADD_OUTCOME_GOAL: "Add Outcomes Goal",
    EDIT_OUTCOME_GOAL: "Edit Outcomes Goal",
    OUTCOME_SECTIONS: "Outcome Sections",
    MISSING_INFO_OUTCOME_SECTION:
      "Unable to get, create, edit and delete outcome sections. Please ensure you are properly logged in to GHL with an active location selected.",
    CREATED_SUCCESS_OUTCOME_SECTION: "Outcome Section Created Successfully",
    UPDATED_SUCCESS_OUTCOME_SECTION: "Outcome Section Updated Successfully",
    DELETE_SUCCESS_OUTCOME_SECTION: "Outcome Section Deleted Successfully",
    FETCH_ERROR_OUTCOME_SECTION: "Failed to fetch the outcome sections",
    DELETE_ERROR_OUTCOME_SECTION: "Failed to delete the outcome section",
    RENAME: "Rename",
    FOR_ALL_OUTCOMES: " for all outcome goals where it is used:",
    DELETE: "Delete",
    FROM_OUTCOME_SECTIONS: "from outcome sections.",
    ADD_OUTCOME_SECTION: "Add Outcome Section",
    OUTCOME_STATUSES: "Outcome Statuses",
    MISSING_INFO_OUTCOME_STATUS:
      "Unable to get, create, edit and delete outcome statuses. Please ensure you are properly logged in to GHL with an active location selected.",
    CREATED_SUCCESS_OUTCOME_STATUS: "Outcome Status Created Successfully",
    UPDATED_SUCCESS_OUTCOME_STATUS: "Outcome Status Updated Successfully",
    DELETE_SUCCESS_OUTCOME_STATUS: "Outcome Status Deleted Successfully",
    FETCH_ERROR_OUTCOME_STATUS: "Failed to fetch the outcome statuses",
    DELETE_ERROR_OUTCOME_STATUS: "Failed to delete the outcome status",
    FROM_OUTCOME_STATUSES: "from outcome statuses.",
    ADD_OUTCOME_STATUS: "Add Outcome Status",
    DELETE_GOAL: "Delete Goal",
    DELETE_GOAL_DESC: "Are you sure you want to delete this goal?",
    OUTCOMES_FOR: "Outcomes for",
    ADD_GOAL_SET: "Add Goal Set",
    EDIT_GOAL_SET: "Edit Goal Set",
    EMPTY_OUTCOME_TITLE: "Add Goal Set and Start Outcomes",
    EMPTY_OUTCOME_DESC:
      "The outcomes feature allows you to collaboratively track the progress of a case through a defined set of goals. Agents can view and mark the status of each goal, add comments, view a modification history and generate a case report including outcomes progress.",
    EMPTY_OUTCOME_DESC1:
      'With this latest version of Outcomes you can create multiple groups of goals called "Goal Sets". With multiple goal sets, you can have a set of outcomes that only your agency can see with the privacy settings.',
    ADD_GOAL_SET_WARNING: "This case and anything added is only visible to",
    VISIBLE_TO: "Visible to",
    CHOOSE_CUSTOM_GOALS: "Choose Outcome Goals",
    CHOOSE_CUSTOM_GOALS_INFO:
      "This list is managed by the network administrator because it is shared for all cases, but you are not limited to only using these goals.",
    CHOOSE_CUSTOM_GOALS_INFO1:
      'Once you click "Add Goal Set" at the bottom of this window, you can add in your own custom goals by clicking the "Edit" button to the right of each section title.',
    SELECT_ALL_GOALS: "Select All Goals",
    GOALS: "Goals",
    INCLUDE: "Include",
    CREATED_BY: "Created by: ",
    COMPLETE: "Complete",
    GOALS_COMPLETED: "Goals Completed",
    DELETE_GOAL_SET: "Delete Goal Set",
    DELETE_GOAL_SET_DESC:
      "Are you sure you want to delete this outcomes goal set?",
    PRINT_OUTCOME_WORKSHEET: "Print Outcome Worksheet",
    PRINT_WORKSHEET: "Print Worksheet",
    SELECT_GOALS_TO_INCLUDE: "Select Goals To Include (Skip To Include All)",
    INCLUDE_COMMENTS: "Include comments",
    SHOW_FILES_COMMENTS: "SHOW MODIFICATIONS - FILES - COMMENTS",
    ADD_COMMENT_FILE: "ADD COMMENT / FILE",
    ATTACHED_FILE: "Attached File",
    POSTED_BY: "Posted by",
    UPDATE_OUTCOME_GOALS: "Update Outcome Goals",
    STATUS: "Status",
    DUE_DATE: "Due Date",
    EMAIL_NOTIFICATIONS: "Email Notifications",
    STEPS: "Steps",
    ADD_CUSTOM_GOALS: "Add Custom Goal",
  },
  NOTES: {
    ADD_NOTES: "Add Notes",
    NOTES: "Notes",
    EDIT_NOTE: "Edit Note",
    SAVE_CHANGES: "Save Changes",
    NOTE_ADDED_SUCCESS: "Note added successfully!",
    NOTE_UPDATED_SUCCESS: "Note updated successfully!",
    NOTE_DELETED_SUCCESS: "Note deleted successfully!",
    CONFIRM_DELETE_TITLE: "Delete Note",
    CONFIRM_DELETE_MESSAGE:
      "Are you sure you want to permanently delete this note? This action cannot be undone.",
    DELETE_NOTE_BUTTON: "Delete Note",
    MISSING_DATA: "Missing case, user, or location data.",
    NOTE_ADDED_FOR: "Note added for",
    ATTACHED_FILES: "Attached Files",
    A_NOTE: "a note",
  },
  CASE_DETAILS: {
    SHOW: "Show",
    ASSISTANCE_FOR: "assistance for...",
    LIVING_WITH: "Living with",
    RELATED: "Related",
    ADD_REQUEST: "Add Request/Referral",
    ADD_ASSISTANCE: "Add Assistance",
    FILTER_BY: "Filter By",
    ADD_DOCUMENT: "Add Document",
  },
  DOCUMENTS: {
    ADD_DOCUMENT: "Add Document",
    DOCUMENTS: "Documents",
    EDIT_DOCUMENT: "Edit Document",
    SAVE_CHANGES: "Save Changes",
    DOCUMENT_ADDED_SUCCESS: "Document added successfully!",
    DOCUMENT_UPDATED_SUCCESS: "Document updated successfully!",
    DOCUMENT_DELETED_SUCCESS: "Document deleted successfully!",
    CONFIRM_DELETE_TITLE: "Delete Document",
    CONFIRM_DELETE_MESSAGE:
      "Are you sure you want to permanently delete this document? This action cannot be undone.",
    DELETE_DOCUMENT_BUTTON: "Delete Document",
    MISSING_DATA: "Missing case, user, or location data.",
    ATTACHED_FILES: "Attached Files",
    DOWNLOAD: "Download",
    UPLOADED_BY: "Uploaded by",
  },
  ALERTS: {
    ADD_ALERT: "Add Alert",
    ALERTS: "Alerts",
    EDIT_ALERT: "Edit Alert",
    SAVE_CHANGES: "Save Changes",
    ALERT_ADDED_SUCCESS: "Alert added successfully!",
    ALERT_UPDATED_SUCCESS: "Alert updated successfully!",
    ALERT_DELETED_SUCCESS: "Alert deleted successfully!",
    CONFIRM_DELETE_TITLE: "Delete Alert",
    CONFIRM_DELETE_MESSAGE:
      "Are you sure you want to permanently delete this alert? This action cannot be undone.",
    DELETE_ALERT_BUTTON: "Delete Alert",
    MISSING_DATA: "Missing case, user, or location data.",
    SEND_EMAIL_LABEL: "Send email alert to all agencies?",
    DESCRIPTION_LABEL: "Description",
    DESCRIPTION_REQUIRED: "Description is required",
    ADDED_FOR: "Alerts added for",
  },
  GLOBAL_SEARCH: {
    ADVANCED_SEARCH_TITLE: "Advanced Search",
    RESET_SEARCH: "Reset Search",
    HEAD_OF_HOUSEHOLD_FILTER: "Only show HEAD of HOUSEHOLD in search results.",
    SEARCH_RESULTS_TITLE: "Search Results",
    NO_CASE_FOUND_PROMPT: "Don't see the case you're looking for?",
    CREATE_CASE_LINK: "Click here to create a case",
    FROM_SEARCH_TERMS: "from your search terms.",
    BACK_TO_BASIC_SEARCH: "Back to Basic Search",
  },
  SIDEBAR: {
    QUICK_ACTIONS: "Quick Actions",
    RECENT_CASES: "Recent Cases",
    RECENT_SEARCHES: "Recent Searches",
    NO_RECENT_SEARCHES: "No recent searches.",
  },
  BARCODES: {
    PRINT_BARCODES: "Print Barcodes",
    ADD_BARCODE: "Add Barcode",
    GLOBAL_BARCODES_TITLE: "Global Barcodes",
    GLOBAL_BARCODES_DESC:
      "Available to all agencies and managed by network administrators",
    AGENCY_BARCODES_TITLE: "Agency Barcodes",
    AGENCY_BARCODES_DESC:
      "Available to only your agency and managed by your agency and network administrators",
    BARCODE_ADDED: "Barcode added!",
    BARCODE_UPDATED: "Barcode updated!",
    BARCODE_DELETED: "Barcode deleted!",
    DELETE_CONFIRM: "Are you sure you want to delete this barcode?",
    NO_BARCODES: "No barcodes found",
  },
  BED_ASSIGNMENTS: {
    ADD_BED_REQUEST: "Add Bed Request",
    ASSIGN_BED: "Assign Bed",
    CASE: "Case",
    REQUESTED_AGENCY: "Requested Agency",
    REQUESTED_SITE: "Requested Site",
    DATE_OF_ARRIVAL: "Date of Arrival",
    NOTES: "Notes",
    CHECK_IN: "Check In",
    CHECK_OUT: "Check Out",
    AGENCY: "Agency",
    BED_NAME: "Bed Name",
    BED_ROOM: "Bed Room",
    BED_TYPE: "Bed Type",
    SITE: "Site",
    DENIAL_REASON: "Denial Reason",
  },
  REFERRALS: {
    THIS_REQUEST_REFERRED_TO: "This request has been referred to:",
    CHOOSE_DIFFERENT_AGENCY:
      "Choose a different agency/service for this referral.",
    UPDATE_STATUS: "Update Status",
    ADD_REQUESTED_ASSISTANCE: "Add Requested Assistance",
    OR: "or",
    STATUS_HISTORY: "Status History",
    REQUESTED_ASSISTANCE: "Requested Assistance",
    STATUS_UPDATED: "Status updated successfully",
    STATUS_UPDATE_FAILED: "Failed to update status",
    REFERRAL_CREATED: "Referral created successfully",
    REFERRAL_UPDATED: "Referral update successfully",
    REFERRAL_DELETED: "Referral deleted successfully",
    REFERRAL_CREATE_FAILED: "Failed to create referral",
    REFERRAL_UPDATE_FAILED: "Failed to update referral",
    REFERRAL_DELETE_FAILED: "Failed to delete referral",
    REQUESTED_BY: "Requested by",
    MISSING_INFO: "Missing information for deletion.",
    DELETE_FAILED: "Failed to delete referral",
    UPDATE_STATUS_FAILED: "Failed to update status",
    CREATE_FAILED: "Failed to create referral",
    UPDATE_FAILED: "Failed to update referral",
    FETCH_SERVICE_ERROR: "Failed to fetch services",
    FETCH_UNITS_ERROR: "Failed to fetch units",
  },
  EVENTS: {
    MISSING_INFO:
      "Unable to get, create, edit and delete event activity. Please ensure you are properly logged in to GHL with an active location selected.",
    CREATED_SUCCESS: "Event Activity Created Successfully",
    UPDATED_SUCCESS: "Event Activity Updated Successfully",
    FETCH_ERROR: "Failed to fetch the event activities",
    MISSING_INFO_LOCATION:
      "Unable to get, create, edit and delete event location. Please ensure you are properly logged in to GHL with an active location selected.",
    CREATED_SUCCESS_LOCATION: "Event Location Created Successfully",
    UPDATED_SUCCESS_LOCATION: "Event Location Updated Successfully",
    DELETE_SUCCESS_LOCATION: "Event Location Deleted Successfully",
    FETCH_ERROR_LOCATION: "Failed to fetch the event location",
    DELETE_ERROR_LOCATION: "Failed to delete the event location",
    MISSING_INFO_EVENT_TYPE:
      "Unable to get, create, edit and delete events type. Please ensure you are properly logged in to GHL with an active location selected.",
    CREATED_SUCCESS_EVENT_TYPE: "Event Type Created Successfully",
    UPDATED_SUCCESS_EVENT_TYPE: "Event Type Updated Successfully",
    DELETE_SUCCESS_EVENT_TYPE: "Event Type Deleted Successfully",
    DELETE_ERROR_EVENT_TYPE: "Failed to delete the event type",
    FETCH_ERROR_EVENTS_TYPE: "Failed to fetch the event type",
    MISSING_INFO_EVENT:
      "Unable to get, create, edit and delete event. Please ensure you are properly logged in to GHL with an active location selected.",
    CREATED_SUCCESS_EVENT: "Event Created Successfully",
    UPDATED_SUCCESS_EVENT: "Event Updated Successfully",
    DELETE_SUCCESS_EVENT: "Event Deleted Successfully",
    FETCH_ERROR_EVENT: "Failed to fetch the event",
    DELETE_ERROR_EVENT: "Failed to delete the event",
    MANAGE_EVENT_TYPES: "Manage Event Types",
    RENAME: "Rename",
    FOR_ALL_EVENTS: "for all events where it is used:",
    DELETE: "Delete",
    FROM_EVENT_TYPE: "from event types.",
    ADD_NEW_EVENT_TYPE: "Add New Event Type",
  },
  SERVICES: {
    ADD_SERVICES: "Add Services",
    EDIT_SERVICE: "Edit Service",
    DELETE_SERVICE: "Delete Service",
    DELETE_SERVICE_CONFIRM:
      "Are you sure you want to delete this service? This action cannot be undone.",
    DELETE_SUCCESS: "Service deleted successfully",
    UPDATE_SUCCESS: "Service updated successfully",
    CREATE_SUCCESS: "Service created successfully",
    MISSING_DATA:
      "User or location data missing. Cannot perform service operation.",
    FETCH_ERROR: "Failed to fetch services",
    CREATE_ERROR: "Failed to create service",
    UPDATE_ERROR: "Failed to update service",
    DELETE_ERROR: "Failed to delete service",
    NO_PERMISSION: "You don't have permission to perform this action",
  },
  ASSESSMENT: {
    ADD_FIELD_TITLE: "Add Form Field",
    ADD_FIELD_BUTTON: "Add Form Field",
    FIELD_NAME_LABEL: "Field Label",
    FIELD_TYPE_LABEL: "Field Type",
    FIELD_TYPE_CHECKBOX: "Checkbox",
    FIELD_TYPE_DATE: "Date",
    FIELD_TYPE_RADIO: "Radio Buttons",
    FIELD_TYPE_DROPDOWN: "Dropdown",
    FIELD_TYPE_WHOLE_NUMBER: "Whole number",
    FIELD_TYPE_DECIMAL_NUMBER: "Decimal number",
    FIELD_TYPE_TEXT: "Short Text",
    FIELD_TYPE_TEXTAREA: "Long Text",
    PAGE_TITLE: "Assessment Fields",
    MOVE_UP: "Move Up",
    MOVE_DOWN: "Move Down",
    ASSESSMENTS: "Assessments",
    ASSESSMENTS_FOR: "Assessments for",
    ADD_ASSESSMENT: "Add Assessment",
    ASSESSMENT_FOR: "Assessment for",
    SHOW: "Show",
    MODIFICATIONS: "Modifications",
    COMMENTS: "Comments",
    COMMENT_POSTED_BY: "Comment posted by",
    SHOW_DETAILS: "Show Details",
    HIDE_DETAILS: "Hide Details",
    HIDE_COMPARISON_TABLE: "Hide Assessment Comparison Table",
    SHOW_COMPARISON_TABLE: "Show Assessment Comparison Table",
    QUESTIONS: "Questions",
    YES: "Yes",
    NO: "No",
  },
  DASHBOARD: {
    WELCOME: "Welcome 👋",
    WELCOME_DESC:
      "Track your community's impact and spread kindness. Together, we can make a difference in people's lives.",
    COMMUNITY_DASHBOARD: "Community Dashboard",
    AGENTS: "Agents",
    ACCESS: "Access",
    CASES: "Cases",
    ENGAGE: "Engage",
    SERVICES: "Services",
    TRACK: "Track",
    TASKS: "Tasks",
    OVERDUE: "Overdue",
    NO_OVERDUE_TASKS: "No overdue tasks",
  },
  REPORTS: {
    REPORT: "Report",
    VIEW_REPORT: "View Report",
    CHOOSE_FILTERS: "Choose Filters for",
    CHOOSE_CASE: "Filter by case (Skip To Include All)",
    CHOOSE_CATEGORY: "Filter by category (Skip To Include All)",
  },
};

export const LABELS = {
  FORM: {
    NAME: "Name",
    FIRST_NAME: "First Name",
    LAST_NAME: "Last Name",
    EMAIL: "Email",
    PHONE: "Phone",
    ADDRESS: "Address",
    MAILING_ADDRESS: "Mailing Address",
    CITY: "City",
    STATE: "State",
    ZIP: "ZIP Code",
    COUNTRY: "Country",
    PASSWORD: "Password",
    CONFIRM_PASSWORD: "Confirm Password",
    PROVIDED_BY: "Provided by",
    DESCRIPTION: "Description",
    ATTACH_FILE: "Attach a file",
    VISIBLE_TO: "Visible to",
    VISIBLE_TO_DESC: "This case and anything added is only visible to",
    CASE_ID: "Case ID",
    DOB: "Date of Birth (MM-DD-YYYY)",
    SSN: "SS Number",
    AMOUNT: "Amount",
    UNIT: "Unit",
    CATEGORY: "Category",
    STATUS: "Status",
    REQUEST_DATE: "Request Date",
    REQUEST_TIME: "Request Time",
    REQUEST_DEADLINE_DATE: "Request Deadline Date",
    REFERRED_AGENCY_SERVICE: "Referred Agency Service",
    REFER_REQUEST_TO_AGENCY: "Refer this request to another agency?",
    CASE: "Case",
    MEMBERS_NEED_BED: "Household Member(s) Needing A Bed",
    AGENCY: "Agency",
    DATE_OF_ARRIAVAL_TEXT: "Date of Arrival",
    DATE_OF_ARRIAVAL: "Date of Arrival (MM-DD-YYYY)",
    SITE: "Site",
    AVAILABLE_BEDS: "Available Bed(S)",
    NOTES: "Notes",
    BED: "Bed",
    CHECKED_IN_DATE: "Check In Date (MM-DD-YYYY)",
    CHECKED_OUT_DATE: "Check Out Date (MM-DD-YYYY)",
    DELETE_BED_REQUEST:
      "Denial Reason (ex. ineligible, bed no longer available)",
    LIST_TITLE: "List Title",
    DESCRIPTION2: "Description (Optional)",
    LOCATION: "Location",
    EVENT_TYPE: "Event Type",
    EVENT_TITLE: "Event Title",
    EVENT_DESC: "Event Description",
    DATE_TIME: "Date & Time",
    FACILITATOR: "Facilitator",
    TYPE: "Type",
    LOCATION_NAME: "Location Name",
    CONTACT_NAME: "Contact Name",
    CONTACT_PHONE: "Contact Phone",
    CONTACT_EMAIL: "Contact Email",
    WHICH_AGENCY: "Specify which agency can use this location",
    NO_RESTICTIONS: "No Restictions (Available to All Agencies)",
    OUTCOMES_SECTION: "Outcomes Section",
    TITLE: "Title",
    LAST_UPDATED: "Last Updated",
    WORKSHEET_TITLE: "Worksheet Title",
    COMMENT: "Comment",
  },
  FILTERS: {
    SHOW_CASES: "Show cases created by:",
    ALL_AGENCIES: "All Agencies",
  },
  PAGINATION: {
    OF: "of",
    ITEMS: "items",
    REFERRALS_RECEIVED: "referrals received",
  },
  CATEGORY: {
    SECTION: "Section",
    NAME: "Category Name",
    DESCRIPTION: "Description",
    DEFAULT_AMOUNT: "Default Amount",
    DEFAULT_UNIT: "Default Unit",
    FIXED_VALUE: "Fixed Value ($)",
  },
  TABLES: {
    BED_LIST: {
      SITE: "Site",
      NAME: "Name",
      ROOM: "Room",
      TYPE: "Type",
      STATUS: "Status",
      CASE_NOTE: "Case / Note",
      CHECK_IN: "Check In",
    },
  },
  REFERRALS: {
    FILTERS: "Filters:",
    DATE: "Date",
    CASE: "Case",
    CATEGORY: "Category",
    AMOUNT: "Amount",
    STATUS: "Status",
    AGENCY: "Agency",
    FILTER_BY_DATE: "Filter by Date : ",
    FILTER_BY_CATEGORY: "Filter by Category : ",
    FILTER_BY_STATUS: "Filter by Status : ",
    DATE_RANGE_TO: "to",
  },
  SERVICE: {
    OPTIONAL_TAXONOMY_CODE: "Optional taxonomy code",
    SECTION: "Section",
  },
};

export const PLACEHOLDERS = {
  SEARCH: {
    AGENCIES: "Search agencies...",
    AGENTS: "Search agents...",
    CASES: "Search cases...",
    SERVICES: "Search services...",
    CATEGORIES: "Search categories...",
    CASE_NUMBER_OR_NAME: "Enter case # or name",
    SEARCH: "Search:",
  },
  FORM: {
    NAME: "Enter name",
    EMAIL: "Enter email",
    PHONE: "Enter phone number",
    ADDRESS: "Enter address",
    DESCRIPTION: "Enter description",
    DATE_PLACEHOLDER: "MM - DD - YYYY",
  },
  CATEGORY: {
    SECTION: "Select section",
    NAME: "Enter category name",
    DESCRIPTION: "Enter description",
    DEFAULT_AMOUNT: "Enter default amount",
    DEFAULT_UNIT: "Select default unit",
    FIXED_VALUE: "Enter fixed value",
  },
};
